const PLACEMENTS = [
  {
    code: "home_top",
    title: "Главная — под шапкой",
    platform: "web",
    width: 970,
    height: 250,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: { carousel: true },
    sort: 10,
  },
  {
    code: "feed_native",
    title: "Лента — нативная карточка",
    platform: "web",
    width: 0,
    height: 0,
    mobileWidth: 0,
    mobileHeight: 0,
    enabled: true,
    config: { interval: 8 },
    sort: 20,
  },
  {
    code: "category_top",
    title: "Категория — баннер над списком",
    platform: "web",
    width: 970,
    height: 250,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: { carousel: true },
    sort: 30,
  },
  {
    code: "search_top",
    title: "Поиск — спонсорский блок",
    platform: "web",
    width: 970,
    height: 120,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: {},
    sort: 40,
  },
  {
    code: "sidebar",
    title: "Боковая колонка, только десктоп",
    platform: "web",
    width: 300,
    height: 600,
    mobileWidth: 300,
    mobileHeight: 250,
    enabled: true,
    config: { sticky: true },
    sort: 50,
  },
  {
    code: "listing_detail",
    title: "Объявление — под фото и под описанием",
    platform: "web",
    width: 728,
    height: 90,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: {},
    sort: 60,
  },
  {
    code: "mobile_sticky_bottom",
    title: "Мобильный браузер — липкий низ",
    platform: "web",
    width: 320,
    height: 50,
    mobileWidth: 320,
    mobileHeight: 50,
    enabled: true,
    config: {},
    sort: 70,
  },
  {
    code: "post_success",
    title: "После публикации объявления",
    platform: "web",
    width: 728,
    height: 90,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: {},
    sort: 80,
  },
  {
    code: "home_mid",
    title: "Главная — между секциями",
    platform: "web",
    width: 970,
    height: 120,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: { carousel: true },
    sort: 90,
  },
  {
    code: "listing_top",
    title: "Каталог — над сеткой",
    platform: "web",
    width: 970,
    height: 120,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: {},
    sort: 100,
  },
  {
    code: "listing_feed",
    title: "Каталог — в ленте (прежний код)",
    platform: "web",
    width: 0,
    height: 0,
    mobileWidth: 0,
    mobileHeight: 0,
    enabled: true,
    config: { interval: 8 },
    sort: 110,
  },
  {
    code: "category_feed",
    title: "Категория — в ленте (прежний код)",
    platform: "web",
    width: 0,
    height: 0,
    mobileWidth: 0,
    mobileHeight: 0,
    enabled: true,
    config: { interval: 8 },
    sort: 120,
  },
  {
    code: "ad_details_mid",
    title: "Объявление — прежний слот",
    platform: "web",
    width: 728,
    height: 90,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: {},
    sort: 130,
  },
  {
    code: "ad_sidebar",
    title: "Объявление — прежний sidebar",
    platform: "web",
    width: 300,
    height: 250,
    mobileWidth: 300,
    mobileHeight: 250,
    enabled: true,
    config: { sticky: true },
    sort: 140,
  },
  {
    code: "footer",
    title: "Над футером",
    platform: "web",
    width: 970,
    height: 90,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: {},
    sort: 150,
  },
  {
    code: "app_home_top",
    title: "Приложение — верх главной",
    platform: "app",
    width: 320,
    height: 100,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: { carousel: true },
    sort: 210,
  },
  {
    code: "app_feed_native",
    title: "Приложение — карточка в ленте",
    platform: "app",
    width: 0,
    height: 0,
    mobileWidth: 0,
    mobileHeight: 0,
    enabled: true,
    config: { interval: 8 },
    sort: 220,
  },
  {
    code: "app_category_top",
    title: "Приложение — верх категории",
    platform: "app",
    width: 320,
    height: 100,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: {},
    sort: 230,
  },
  {
    code: "app_search_top",
    title: "Приложение — над поиском",
    platform: "app",
    width: 320,
    height: 100,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: {},
    sort: 240,
  },
  {
    code: "app_listing_detail",
    title: "Приложение — экран объявления",
    platform: "app",
    width: 320,
    height: 100,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: {},
    sort: 250,
  },
  {
    code: "app_sticky_bottom",
    title: "Приложение — над таб-баром",
    platform: "app",
    width: 320,
    height: 50,
    mobileWidth: 320,
    mobileHeight: 50,
    enabled: true,
    config: {},
    sort: 260,
  },
  {
    code: "app_post_success",
    title: "Приложение — после публикации",
    platform: "app",
    width: 320,
    height: 100,
    mobileWidth: 320,
    mobileHeight: 100,
    enabled: true,
    config: {},
    sort: 270,
  },
  {
    code: "app_interstitial",
    title: "Приложение — полноэкранная",
    platform: "app",
    width: 320,
    height: 480,
    mobileWidth: 320,
    mobileHeight: 480,
    enabled: false,
    config: { interstitial: true },
    sort: 280,
  },
];

const FORMATS = ["banner", "native", "html", "image", "network"];

const ALIASES = {
  feed_native: ["feed_native", "listing_feed", "category_feed"],
  listing_detail: ["listing_detail", "ad_details_mid"],
  sidebar: ["sidebar", "ad_sidebar"],
  app_feed_native: ["app_feed_native"],
};

function listPlacements() {
  return PLACEMENTS.map((item) => item.code);
}

function findPlacement(code) {
  return PLACEMENTS.find((item) => item.code === code) || null;
}

function codesFor(placement) {
  const code = String(placement || "").trim();
  return ALIASES[code] || [code];
}

function placementMatchesPlatform(definition, platform) {
  if (!definition) return true;
  const normalized = String(platform || "web").toLowerCase();

  if (definition.platform === "web") {
    return normalized === "web" || normalized === "site";
  }

  return normalized === "ios" || normalized === "android" || normalized === "app";
}

module.exports = {
  PLACEMENTS,
  FORMATS,
  ALIASES,
  listPlacements,
  findPlacement,
  codesFor,
  placementMatchesPlatform,
};
